# Generated by Django 3.0.5 on 2020-04-25 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('self_user', models.BooleanField(default=True, verbose_name='Self user')),
                ('f_name', models.CharField(max_length=50, verbose_name='First name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('bdate', models.DateField(default=datetime.date(1978, 9, 7), verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('O', 'Nenhum/Outro'), ('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(default='arantesdv@me.com', max_length=254)),
                ('phone', models.CharField(default='+5562', max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(default='Rua Rodrigues Tomaz 95 Jundiaí', max_length=200, verbose_name='Address')),
                ('city', models.CharField(default='Anápolis', max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('DF', 'Distrito Federal'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='GO', max_length=2, verbose_name='State')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=12)),
                ('is_patient', models.BooleanField(default=False, editable=False, verbose_name='Is patient')),
                ('is_doctor', models.BooleanField(default=False, editable=False, verbose_name='Is doctor')),
                ('is_nurse', models.BooleanField(default=False, editable=False, verbose_name='Is nurse')),
                ('doctor_status', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('self_user', models.BooleanField(default=True, verbose_name='Self user')),
                ('f_name', models.CharField(max_length=50, verbose_name='First name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('bdate', models.DateField(default=datetime.date(1978, 9, 7), verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('O', 'Nenhum/Outro'), ('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(default='arantesdv@me.com', max_length=254)),
                ('phone', models.CharField(default='+5562', max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(default='Rua Rodrigues Tomaz 95 Jundiaí', max_length=200, verbose_name='Address')),
                ('city', models.CharField(default='Anápolis', max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('DF', 'Distrito Federal'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='GO', max_length=2, verbose_name='State')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=12)),
                ('is_patient', models.BooleanField(default=False, editable=False, verbose_name='Is patient')),
                ('is_doctor', models.BooleanField(default=False, editable=False, verbose_name='Is doctor')),
                ('is_nurse', models.BooleanField(default=False, editable=False, verbose_name='Is nurse')),
                ('patient_status', models.BooleanField(default=True, verbose_name='Is active')),
                ('doctors', models.ManyToManyField(blank=True, related_name='patient_doctors', to='accounts.Doctor')),
                ('family', models.ManyToManyField(blank=True, related_name='patient_family', to='accounts.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('meta_keywords', models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('meta_observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('self_user', models.BooleanField(default=True, verbose_name='Self user')),
                ('f_name', models.CharField(max_length=50, verbose_name='First name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('bdate', models.DateField(default=datetime.date(1978, 9, 7), verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('O', 'Nenhum/Outro'), ('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(default='arantesdv@me.com', max_length=254)),
                ('phone', models.CharField(default='+5562', max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(default='Rua Rodrigues Tomaz 95 Jundiaí', max_length=200, verbose_name='Address')),
                ('city', models.CharField(default='Anápolis', max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('DF', 'Distrito Federal'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='GO', max_length=2, verbose_name='State')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=12)),
                ('is_patient', models.BooleanField(default=False, editable=False, verbose_name='Is patient')),
                ('is_doctor', models.BooleanField(default=False, editable=False, verbose_name='Is doctor')),
                ('is_nurse', models.BooleanField(default=False, editable=False, verbose_name='Is nurse')),
                ('nurse_status', models.BooleanField(default=True, verbose_name='Is active')),
                ('patients', models.ManyToManyField(blank=True, related_name='nurse_patients', to='accounts.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctor_patients', to='accounts.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nurse',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'bdate', 'gender'), name='unique_profile'),
        ),
    ]
