# Generated by Django 3.0.5 on 2020-04-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='family',
        ),
        migrations.CreateModel(
            name='ConsanguineFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.PositiveSmallIntegerField(choices=[(1, 'Mother'), (2, 'Father'), (3, 'Sibling'), (4, 'Offspring'), (5, 'Second degree relatives')])),
                ('confidense', models.PositiveSmallIntegerField(choices=[(1, 'Mínima'), (2, 'Baixa'), (3, 'Moderada'), (4, 'Elevada'), (5, 'Máxima')])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relater_patient', to='accounts.Patient')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relative', to='accounts.Patient')),
            ],
        ),
    ]
