# Generated by Django 3.0.5 on 2020-04-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200425_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsanguineFamily',
            new_name='ConsanguineRelation',
        ),
    ]
